//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalesWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AutosalesContext : DbContext
    {
        public AutosalesContext()
            : base("name=AutosalesContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
            this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DealershipProductTarget> DealershipProductTargets { get; set; }
        public DbSet<Dealership> Dealerships { get; set; }
        public DbSet<Employee> Employees { get; set; }
        public DbSet<Product> Products { get; set; }
        public DbSet<Region> Regions { get; set; }
        public DbSet<SalesTransaction> SalesTransactions { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<DealershipAward> DealershipAwards { get; set; }
        public DbSet<DealershipService> DealershipServices { get; set; }
        public DbSet<EmployeeAward> EmployeeAwards { get; set; }
        public DbSet<ProductAward> ProductAwards { get; set; }
    }
}
