//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalesWebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Dealership
    {
        public Dealership()
        {
            this.DealershipProductTargets = new HashSet<DealershipProductTarget>();
            this.Employees = new HashSet<Employee>();
            this.SalesTransactions = new HashSet<SalesTransaction>();
            this.DealershipAwards = new HashSet<DealershipAward>();
            this.DealershipServices = new HashSet<DealershipService>();
        }
    
        public string ID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public Nullable<float> Latitude { get; set; }
        public Nullable<float> Longitude { get; set; }
        public string Country { get; set; }
        public string Name { get; set; }
        public string Region { get; set; }
        public string EstablishDate { get; set; }
        public string Image { get; set; }
        public string GeneralManager { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
    
        [JsonIgnore]
        public virtual ICollection<DealershipProductTarget> DealershipProductTargets { get; set; }
        [JsonIgnore]
        public virtual ICollection<Employee> Employees { get; set; }
        [JsonIgnore]
        public virtual ICollection<SalesTransaction> SalesTransactions { get; set; }
        [JsonIgnore]
        public virtual ICollection<DealershipAward> DealershipAwards { get; set; }
        [JsonIgnore]
        public virtual ICollection<DealershipService> DealershipServices { get; set; }
    }
}
