//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalesWebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAward
    {
        public int ID { get; set; }
        public string EmployeeID { get; set; }
        public string Award { get; set; }
    
        [JsonIgnore]
        public virtual Employee Employee { get; set; }
    }
}
