//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalesWebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.SalesTransactions = new HashSet<SalesTransaction>();
            this.EmployeeAwards = new HashSet<EmployeeAward>();
        }
    
        public string ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string DealershipID { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<float> YearlyRevenueTarget { get; set; }
        public Nullable<float> YearlyVolumeTarget { get; set; }
        public string Image { get; set; }

        [JsonIgnore]
        public virtual Dealership Dealership { get; set; }
        [JsonIgnore]
        public virtual ICollection<SalesTransaction> SalesTransactions { get; set; }
        [JsonIgnore]
        public virtual ICollection<EmployeeAward> EmployeeAwards { get; set; }
    }
}
