//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalesWebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.DealershipProductTargets = new HashSet<DealershipProductTarget>();
            this.SalesTransactions = new HashSet<SalesTransaction>();
            this.ProductAwards = new HashSet<ProductAward>();
        }
    
        public string SKU { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Category { get; set; }
        public Nullable<float> UnitCost { get; set; }
        public Nullable<float> YearlyRevenueTarget { get; set; }
        public Nullable<float> YearlyVolumeTarget { get; set; }
        public Nullable<int> HP { get; set; }
        public Nullable<int> Doors { get; set; }
        public string Model { get; set; }
        public string MilesPerGallon { get; set; }
        public Nullable<float> SafetyRanking { get; set; }
        public Nullable<float> ConsumerRating { get; set; }
        public string UseCategory { get; set; }
        public string Image { get; set; }

        [JsonIgnore]
        public virtual ICollection<DealershipProductTarget> DealershipProductTargets { get; set; }
        [JsonIgnore]
        public virtual ICollection<SalesTransaction> SalesTransactions { get; set; }
        [JsonIgnore]
        public virtual ICollection<ProductAward> ProductAwards { get; set; }
    }
}
