//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutosalesWebAPI.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class SalesTransaction
    {
        public string ID { get; set; }
        public string EmployeeID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public string ProductSKU { get; set; }
        public Nullable<float> ProductUnitCost { get; set; }
        public Nullable<int> ProductQuantity { get; set; }
        public Nullable<float> ProductTotalCost { get; set; }
        public string DealershipID { get; set; }

        [JsonIgnore]
        public virtual Dealership Dealership { get; set; }
        [JsonIgnore]
        public virtual Employee Employee { get; set; }
        [JsonIgnore]
        public virtual Product Product { get; set; }
    }
}
